sudo: required
services:
  - docker

before_install:
  - docker build -t nitinjain786/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nitinjain786/react-test npm test -- --coverage


after_success:
  - docker build -t  nitinjain786/multi-client ./client
  - docker build -t  nitinjain786/multi-nginx ./nginx
  - docker build -t  nitinjain786/multi-server ./server
  - docker build -t  nitinjain786/multi-worker ./worker


  #  Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin



  # Take those images and push them to docker hub

  - docker push nitinjain786/multi-client
  - docker push nitinjain786/multi-nginx
  - docker push nitinjain786/multi-server
  - docker push nitinjain786/multi-worker



